- Project.toml
- README.md
- examples/README.jl
- src/blocksparsearrayinterface/blocksparsearrayinterface.jl
- test/basics/test_basics.jl
- test/runtests.jl
> Fix setting zero dimensional block

- Project.toml
- src/abstractblocksparsearray/map.jl
- test/basics/test_basics.jl
> Fix zero-dimensional conversion

- Project.toml
- src/abstractblocksparsearray/views.jl
- test/test_svd.jl
This resolves some issues with the broken SVD tests.
Depends on https://github.com/ITensor/SparseArraysBase.jl/pull/23
Fixes #32
> Fix broken SVD tests

- Project.toml
- ext/BlockSparseArraysGradedUnitRangesExt/BlockSparseArraysGradedUnitRangesExt.jl
- test/test_aqua.jl
- test/test_gradedunitrangesext.jl
Hit when working on https://github.com/ITensor/QuantumOperatorDefinitions.jl/pull/22.
> Fix ambiguities with BlockArrays.jl

- Project.toml
- ext/BlockSparseArraysGradedUnitRangesExt/BlockSparseArraysGradedUnitRangesExt.jl
- test/test_gradedunitrangesext.jl
In combination with https://github.com/ITensor/TypeParameterAccessors.jl/pull/36, this fixes a bug I was hitting using `similar` with graded axes when the input is a `BitArray`.
Todo:
> Make `similar` with graded axes more generic

- .github/workflows/IntegrationTest.yml
- Project.toml
Related to https://github.com/ITensor/TensorAlgebra.jl/pull/29.
Depends on https://github.com/ITensor/TypeParameterAccessors.jl/pull/36 and https://github.com/ITensor/BlockSparseArrays.jl/pull/48 to get downstream tests passing.
> Add IntegrationTest workflow

- Project.toml
- ext/BlockSparseArraysTensorAlgebraExt/BlockSparseArraysTensorAlgebraExt.jl
- test/test_gradedunitrangesext.jl
Fixes #50
Non blocksorted axes were used to index an array whose axes are blocksorted. Therefore the intermediary arrays carries invalid blocks. This is a quickfix that returns the correct result, but the code can be improved.
> Fix splitdims(::BlockSparseArrays)

- Project.toml
- src/blocksparsearrayinterface/broadcast.jl
- test/test_basics.jl
This helps to fix https://github.com/ITensor/NamedDimsArrays.jl/issues/17, #37.
> Better overloading of `similar` of block sparse broadcasting expressions

- Project.toml
- src/abstractblocksparsearray/abstractblocksparsearray.jl
- src/blocksparsearray/blocksparsearray.jl
- test/test_basics.jl
Fixes #63, using the same code pattern that was used in https://github.com/ITensor/NamedDimsArrays.jl/pull/48.
The show methods also have to be updated to reflect the changes @lkdvos made in https://github.com/ITensor/SparseArraysBase.jl/pull/31, but this is orthogonal to that issue since this PR is only about how the types are printed, not how the unstored values are printed.
> Fix generic show for block sparse arrays

- Project.toml
- src/abstractblocksparsearray/abstractblocksparsearray.jl
Followup to #65, this function isn't needed anymore but I forgot to delete it.
> Delete unneeded show helper function

- Project.toml
- src/abstractblocksparsearray/views.jl
- src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl
- src/blocksparsearrayinterface/blocksparsearrayinterface.jl
- test/test_basics.jl
> Fix adapting and printing subarrays

- Project.toml
- src/blocksparsearray/blocksparsearray.jl
- test/test_basics.jl
Fixes #108 
```julia
using BlockSparseArrays
a = BlockSparseArray{Float64,2,Matrix{Float64}}(undef, ([2, 2], [2, 2])) # works
a = BlockSparseArray{Float64,2,Matrix{Float64}}(undef, ([2, 2],)) # should error - instead hangs indefinitely
```
By explicitly checking the length and throwing an error.
The alternative would be to simply restrict that constructor to only take length `N` tuples, which would throw a `MethodError` instead.
> [Fix] Stackoverflow in `BlockSparseArray` constructor with wrong number of axes

- Project.toml
- src/BlockArraysExtensions/BlockArraysExtensions.jl
- src/blocksparsearrayinterface/blocksparsearrayinterface.jl
- src/blocksparsearrayinterface/map.jl
This defines a simpler codepath for `map!` when the blocking of the inputs are all the same, so then the mapping can be performed blockwise.
@ogauthe this should help with map operations when the blocks have Kronecker structures.
> Define simpler codepath for blockwise map

- Project.toml
- src/factorizations/svd.jl
This is a followup to #114. While working on https://github.com/ITensor/GradedArrays.jl/pull/33, I realized #114 wasn't quite general enough to account for certain equivariant tensors and block sizes/distributions.
> Make SVD a bit more customizable

- Project.toml
- src/BlockSparseArrays.jl
- src/factorizations/polar.jl
- test/test_factorizations.jl
> Implement blockwise polar decomposition

- Project.toml
- src/abstractblocksparsearray/linearalgebra.jl
- test/test_factorizations.jl
Start adding support for [matrix functions](https://en.wikipedia.org/wiki/Analytic_function_of_a_matrix) such as `exp(A)`, `cos(A)`, `inv(A)`, etc. on square block diagonal matrices. The operations are applied to the diagonal blocks. Care is taken to instantiate unstored diagonal blocks in case they are nontrivial (or even if they remain zero they get instantiated for simplicity).
Matrix functions supported by Julia can be found:
- https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Standard-functions
- https://github.com/JuliaLang/LinearAlgebra.jl/blob/b265feabec34f492ea072a7acacd361a17e5fed7/src/diagonal.jl#L928-L990
- https://github.com/JuliaLang/LinearAlgebra.jl/blob/b265feabec34f492ea072a7acacd361a17e5fed7/src/dense.jl
The strategy to handle this generically is to use …
> Start adding support for matrix functions

- Project.toml
- src/blocksparsearray/blocksparsearray.jl
- test/test_basics.jl
These are the block sparse versions of [`sparse`](https://github.com/ITensor/SparseArraysBase.jl/pull/43) and [`sparsezeros`](https://github.com/ITensor/SparseArraysBase.jl/pull/33).
> Convenient constructors like `blocksparse` and `blocksparsezeros`

- Project.toml
- src/blocksparsearray/blocksparsearray.jl
- src/blocksparsearrayinterface/arraylayouts.jl
- src/factorizations/svd.jl
Splitting off more generalizations from #136.
> More generalizations for generic block types

- Project.toml
- src/BlockArraysExtensions/BlockArraysExtensions.jl
- test/test_basics.jl
> Fix zero-dim `view!`

- Project.toml
- src/blocksparsearrayinterface/map.jl
Followup to https://github.com/ITensor/BlockSparseArrays.jl/pull/150. Make blockwise map/broadcast a bit more customizable by allowing customizing how unstored blocks get constructed. This is helpful for use cases like having blocks that are Kronecker arrays, since it is helpful to construct unstored blocks with Kronecker structures, which this PR enables by overloading `FillArrays.fillsimilar`.
> Make map/broadcast a bit more customizable

- Project.toml
- src/blocksparsearrayinterface/blocksparsearrayinterface.jl
Use [`DerivableInterfaces.permuteddims`](https://github.com/ITensor/DerivableInterfaces.jl/pull/46).
> Use `DerivableInterfaces.permuteddims`
